[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node server/server.js"

# Configure the web service
[webService]
  # The port your web service listens on
  port = 8080
  
  # The directory containing your built frontend files
  staticDir = "build"
  
  # The command to start your Node.js server
  startCommand = "node server/server.js"
